export const keyToHeaderMap = {
  key_0: "District",
  key_1: "PIN",
  key_2: "Address",
  key_3: "Clinic",
  key_4: "Doctor",
  key_5: "Expertise",
  key_6: "Timings",
  key_7: "Phone",
  key_8: "Email",
  key_9: "Online link",
  key_11: "More information",
  key_12: "Website",
  key_10: "info 1",
  key_13: "info 2",
  key_14: "info 3",
};

export type Clinic = {
  key_0: string;
  key_1: string;
  key_2: string;
  key_3: string;
  key_4: string;
  key_5: string;
  key_6: string;
  key_7: string;
  key_8: string;
  key_9: string;
  key_11: string;
  key_12?: string;
  key_10?: string;
  key_13?: string;
  key_14?: string;
};

const data: Clinic[] = [
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10625",
    key_2: "Bismarckstr. 95/96",
    key_3: "MVZ Dr. Kaleth und Kollegen",
    key_4: "Sabine Eigenwillig",
    key_5: "Hausarzt",
    key_6: "Mo.-Fr. 8:00-18:00",
    key_7: "030 / 801 051 50",
    key_8: "info@kaleth-und-kollegen.de",
    key_9: "https://www.doctolib.de/allgemeinm",
    key_10: "",
    key_11: "",
    key_12: "https://www.kalethundkollegen.",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10629",
    key_2: "Schlüterstraße 38",
    key_3: "Praxis Wünsche",
    key_4: "Thoms Wünsche",
    key_5: "Hausarzt",
    key_6:
      "Mo: 8:00-12:30 und 14:00- 19:00 / Di: 8:00-12:30 und 14:00-19:00 / Mi: 7:00- 14:00 / Do: 08:00-12:30 und 14:00-19:00 / Fr: 7:00-14:00",
    key_7: "030 / 885 643 0",
    key_8: "service@praxis-wuensche.com",
    key_9: "www.praxis-wuensche.com",
    key_10: "",
    key_11: "",
    key_12: "https://www.praxis- wuensche.com/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10629",
    key_2: "Dahlmannstr. 7",
    key_3: "Internisten Schlich u. Schorn",
    key_4: "Dr. Kai Schorn",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo,Di,Do 8:00-18:00 Uhr Mi,Fr 8:00-12:00 Uhr",
    key_7: "doctolib",
    key_8: "",
    key_9: "doctolib",
    key_10: "",
    key_11:
      "Keine Impfung bei Menschen unter 30 Jahren. Impfpass, Aufklärungsbogen und Einwilligung (über doctolib ) müssen mitgebracht werden.",
    key_12: "www.internisten.berlin",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10709",
    key_2: "Westfälische Str. 32",
    key_3: "Dr.med.Marlies Machens, Dr.med. Laura Freier",
    key_4: "Dr.med.Marlies Machens, Dr.med. Laura Freier",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Impfsprechstunde: Donnerstag: 11:05-11:50h, 15:00-15:50h",
    key_7: "030 / 895 412 91",
    key_8: "mail@dieinternistin.de",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "https://dieinternistin.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10717",
    key_2: "Bundesallee 185",
    key_3: "Aksü und Seeberger",
    key_4: "Uwe Seeber Tansel Aksü",
    key_5: "Hausärztin/Hausarzt",
    key_6:
      "Montag 9- 14 Uhr und 16 bis 18:00 / Dienatsg 9-14 Uhr und 16- 18:00 / Mittwoch 9 - 12:00 Uhr / Donnerstag 9-14:00 Uhr und 16 - 18:00 Uhr / Freitag 9- 13:00 Uhr",
    key_7: "030 / 218 46 44",
    key_8: "info@praxis-online.biz",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10789",
    key_2: "Rankestraße 8",
    key_3: "MVZ Rankestrasse GmbH",
    key_4: "Dr. Christine Sommerfeld/ Dr. Natascha Hess",
    key_5: "Innere Medizin (fachärztliche Versorgung)",
    key_6:
      "Mo: 9-16 Uhr / Di: 9-15 Uhr / Do: 8-15 Uhr / Fr: 8-13 Uhr Bitte immer nur nach Vereinbarung kommen !",
    key_7: "",
    key_8: "kontakt@mvz-rankestrasse.de",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "https://mvz- rankestrasse.de/aktuelles.html",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "13627",
    key_2: "Reichweindamm 31",
    key_3: "PD Dr. med. Petra Koehne, Fachärzte für Kinder- und Jugendmedizin",
    key_4: "Petra Koehne",
    key_5: "Kinder- und Jugendmedizin",
    key_6:
      "Montag, Dienstag und Donnerstag 09:00-12:00, 15:00-18:00 / Mittwoch 09:00-12:00 / Donnerstag 09:00-12:00, 15:00-18:00 / Freitag 09:00-18:00",
    key_7: "030 / 345 207 1/2",
    key_8: "Praxisteam_Koehne@web.de",
    key_9: "Doctolib",
    key_10: "",
    key_11:
      "Impftermine werden derzeit v.a. am Dienstag und Donnerstag Vormittag, sowie am Mittwoch und Freitag Nachmittag vergeben. Die angebotenen Impfzeiten richten sich v.a. nach der Verfügbarkeit der Impfstoffe. Zum Impftermin mitzubringen sind die Versichertenkarte, der unterschriebene Aufklärungs- und Einwilligungsbogen für die Covid-Impfung (erhältlich auf der Webseite des RKI) und das Impfbuch (sofern vorhanden).",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Matthiasstraße 7",
    key_3: "Facharztzentrum am Friedrichshain",
    key_4: "Dr. med. Knut Krenkel",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Termine nur nach Vereinbarung",
    key_7: "",
    key_8: "corona@facharztzentrum- friedrichshain.de",
    key_9: "Doctolib",
    key_10: "",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Matthiasstraße 7",
    key_3: "Facharztzentrum am Friedrichshain",
    key_4: "Sven Holleck-Weithmann",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6: "Termine nur nach Vereinbarung",
    key_7: "",
    key_8: "corona@facharztzentrum- friedrichshain.de",
    key_9: "Doctolib",
    key_10: "",
    key_11: "",
    key_12: "https://www.facharztzentrum- friedrichshain.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Petersburger Str. 72A",
    key_3: "Chirurgische Praxis",
    key_4: "Dr. Thomas Hofmann",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Freitags",
    key_7: "",
    key_8: "hofmann@hofmann-wierth.de",
    key_9: "",
    key_10: "",
    key_11: "Keine telefonische Anmeldung möglich.",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Petersburger Str. 72A",
    key_3: "chirurgische Praxis Friedrichshain",
    key_4: "Dr. Thomas Hofmann, Dr. Andre Wierth, Robert Krause",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Freitags 12:00-14:30",
    key_7: "",
    key_8: "hofmann@hofmann-wierth.de",
    key_9: "",
    key_10: "",
    key_11: "Impftermine werden auf keine Fall telefonisch vergeben!",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10999",
    key_2: "Kottbusser Straße 16,",
    key_3: "Arztpraxis Dr. Buck",
    key_4: "Dr. Elfriede Buck",
    key_5: "Hausarzt",
    key_6:
      "Montag 10-17 Uhr / Dienstag, Mittwoch, Freitag 10-13 Uhr / Donnerstag 10- 18 Uhr Impfungen erfolgen außerhalb der o.g. Sprechzeiten",
    key_7: "030 / 611 80 76",
    key_8: "",
    key_9: "https://www.doctolib.de/allgemeinm",
    key_10: "",
    key_11:
      "Bitte EInverständniserklärung, Anamnese und Aufklärungsmerkblatt für Vektorimpfstoff ausgefüllt mitbringen (auf der Webseite des RKI erhältlich)",
    key_12: "http://praxisdrbuck.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Lichtenberg",
    key_1: "10315",
    key_2: "Rummelsburgerstr. 13-15",
    key_3: "Facharztpraxis für Allgemeinmedizin",
    key_4: "Dipl. Med. Angela Nöther",
    key_5: "Hausarzt",
    key_6:
      "AstraZeneca-Impfungen außerhalb der Priorisierung ab 03.05.2021 in unserer Praxis möglich, Terminvergabe ausschließlich telefonisch möglich.",
    key_7: "030 / 510 10 13",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11:
      "Für die Impfungen mit dem Astra Impfstoff stehen ausschließlich fixe Termine zur Verfügung, die Ihnen vom Personal angeboten werden. Diese sind abhängig von den Lieferungen des Impfstoffs. Die Impfung von Patienten unter 60 Jahren erfolgt nur auf ausdrücklichen Wunsch des Patienten nach entsprechender Aufklärung. Halten Sie Ihren Impfausweis bereit, kleiden Sie sich bitte praktisch, um lange Wartezeiten zu vermeiden.",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Lichtenberg",
    key_1: "10318",
    key_2: "Rheinsteinstr. 1",
    key_3: "Hausarztpraxis Choi",
    key_4: "Kwang Ryul Choi",
    key_5: "Hausarzt",
    key_6: "Mo-Fr 8:00 -12:00 / Nur Mo und Do 14:00 - 18:00",
    key_7: "030 / 509 01 62",
    key_8: "praxischoi@gmx.de",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Lichtenberg",
    key_1: "10365",
    key_2: "Schulze-Boysen-Straße 35",
    key_3: "Bugenhagen",
    key_4: "Kristin Bugenhagen",
    key_5: "Hausarzt",
    key_6: "Impftag: Mittwochs 07-12 Uhr und nach Vereinbarung",
    key_7: "030 / 553 66 55",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "oder geben Sie unter Tel-Nr Ihren Namen und Rückrufnummer an",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Marzahn-Hellersdorf",
    key_1: "12627",
    key_2: "Hellersdorfer Str. 237",
    key_3: "MVZ für Gynäkologie Helle-Mitte",
    key_4: "Dr. med. Muna Zaghloul-Abu Dakah",
    key_5: "Gynäkologie",
    key_6: "Mo-Do 08:00 - 18:00 / Fr. 08:00 - 12:00",
    key_7: "030 / 290 256 877 030 / 451 99 481 030 / 455",
    key_8: "info@berliner-frauenarzt.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte bringen Sie Ihren Impfausweis und die Versichertenkarte mit. Bei Gerinnungsstörungen bitten wir um Kopien der Befunde.",
    key_12: "www.berliner-kinderwunsch.de",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Seestrasse, 99",
    key_3: "Praxis Tambag",
    key_4: "Sultan Tambag",
    key_5: "Hausärztin/Hausarzt",
    key_6:
      "Montag 8:00-13:00 und 15:00-18:00 Dienstag 8:00-13:00 und 15:00-18:00",
    key_7: "im pftermincorona@gmail.com",
    key_8: "",
    key_9: "",
    key_10:
      "Krankenversicherungskarte, Einverständniserklärung Aufklärungsbogen von der Homepage des Robert-Koch-Instituts",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Lydia Yamin",
    key_5: "Hausarzt",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Mahmoud Pakzad",
    key_5: "Hausarzt",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Peter Velling",
    key_5: "Hausarzt",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Petra Itain",
    key_5: "Hausarzt",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Manuel Moscovici",
    key_5: "Radiologie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Levent Emre",
    key_5: "Radiologie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Jens Alter",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Barbara Schulze",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Afschin Mirschekarnejad",
    key_5: "Chirurgie-Orthopädie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Matthias Bräuer",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Andreas Schief",
    key_5: "Chirurgie-Orthopädie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin die von Ihnen ausgefüllten Aufklärungs- und Anamnesebögen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Lütticher Str. 13",
    key_3: "Praxis Dr. med. Aref Sharafi",
    key_4: "Aref Sharafi",
    key_5: "Innere Medizin (fachärztliche Versorgung)",
    key_6:
      "Montag bis Freitag 09:00- 13:00 Uhr / Montag, Dienstag und Donnerstag 15:00-18:00 Uhr",
    key_7: "030 / 454 90 303",
    key_8: "Sharafi.2018@web.de",
    key_9: "",
    key_10:
      "Liebe Patienten/innen, gerne können Sie sich telefonisch oder per E-Mail unter den aufgelisteten Kontaktdaten, für eine Impfung amelden.",
    key_11: "https://dr-aref- sharafi.business.site/",
  },
  {
    key_0: "Neukölln",
    key_1: "12043",
    key_2: "Karl-Marx-Str., 80",
    key_3: "Tengis Kasch",
    key_4: "Tengis Kasch",
    key_5: "Gynäkologie",
    key_6: "Mo und Di nach Vereinbarung",
    key_7: "030 / 681 50 41",
    key_8: "tengis.kasch@dgn.de",
    key_9: "",
    key_10: "",
    key_11: "https://www.frauenarzt- berlin.de/",
  },
  {
    key_0: "Neukölln",
    key_1: "12043",
    key_2: "Karl-Marx-Straße 78",
    key_3: "Arztpraxis Asafu-Adjaye",
    key_4: "John G. Asafu-Adjaye",
    key_5: "Hausarzt",
    key_6:
      "Montag, Dienstag, Donnerstag von 9 - 13 Uhr und 16 - 18 Uhr / Mittwoch und Freitag von 9 - 13 Uhr",
    key_7: "030 / 623 47 39",
    key_8: "arztpraxis-asafu-adjaye@web.de",
    key_9: "",
    key_10: "Termine zurzeit nur nach vorheriger Vereinbarung.",
    key_11:
      "https://www.arztpraxis-asafu- adjaye.de/praxis/herzlich- willkommen.html",
  },
  {
    key_0: "Neukölln",
    key_1: "12047",
    key_2: "Bürknerstraße 32",
    key_3: "Praxis am Maybachufer - Dr. med. Stefan Karakaya",
    key_4: "Stefan Karakaya",
    key_5: "Hausarzt",
    key_6: "siehe Praxishomepage",
    key_7: "",
    key_8: "",
    key_9: "www.praxis-am-maybachufer.de",
    key_10: "Terminvereinbarung für AstraZeneca ausschließlich online",
    key_11: "https://www.praxis-am- maybachufer.de/de/",
  },
  {
    key_0: "Neukölln",
    key_1: "12055",
    key_2: "Böhmische Str. 45",
    key_3: "Michaud",
    key_4: "Larissa",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo-Fr 9:00 - 12:00 Mo. Di. u. Do. 15:00 - 17:00",
    key_7: "030 / 684 34 77",
    key_8: "dr.michaud@t-online.de",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Neukölln",
    key_1: "12349",
    key_2: "Christoph-Ruden-Strasse 7",
    key_3: "HNO-Facharztpraxis",
    key_4: "Sousan Moghaddam",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6:
      "Montag: 9.00 - 12.00 und 14.00 - 18.00 Uhr Dienstag: 9.00 - 13.00 Uhr Mittwoch: 9.00 - 15.00 Uhr Donnerstag: 12.00 - 18.00 Uhr Freitag: 9.00 - 12. 00 Uhr",
    key_7: "030 / 698 15 041",
    key_8: "arzt@hno-moghaddam.de",
    key_9: "",
    key_10:
      "AstraZeneca für Impfwillige ab 60 Jahren, unter 60jährige freiwillig impfende Ärztinnen: Sousan Moghaddam, Sabine Baran",
    key_11: "www.hno-moghaddam.de",
  },
  {
    key_0: "Neukölln",
    key_1: "12349",
    key_2: "Alt-Buckow 9-11",
    key_3: "Hautarztpraxis",
    key_4: "Dres. Annette und Axel Köhler",
    key_5: "Haut- und Geschlechtskrankheiten",
    key_6: "Nach telefonischer oder persönlicher Absprache",
    key_7: "030 / 660 066 33",
    key_8: "",
    key_9: "",
    key_10:
      "Impfausweis mitbringen Ausgefüllter Aufklärungsbogen (unterschrieben), Anamnese und Einverständniserklärung unterschrieben mitzubringen",
    key_11: "https://berlin-derma.de/",
  },
  {
    key_0: "Pankow",
    key_1: "10437",
    key_2: "Stargarder Str.69/ Eberswalder Str.33",
    key_3: "die hausärzte",
    key_4: "Silke Weck",
    key_5: "Hausarzt",
    key_6:
      "Mo-Fr: 11-13 Uhr in 10437 Berlin, Eberswalder Str.33 (auf dem Hof) - Impfung ausschließlich an diesem Standort - nur mit Termin",
    key_7: "0176 / 202 001 16",
    key_8: "",
    key_9: "www.die-hausaerzte.berlin",
    key_10:
      "Bringen Sie, wenn möglich, das ausgefüllte Aufklärungsmerkblatt und den ausgefüllten Anamnesebogen zum Termin mit. Diese erhalten Sie unter www.RKI.de/Informationsmaterial zum Impfen mit Vektorimpfstoff",
    key_11: "https://www.die- hausaerzte.berlin/",
  },
  {
    key_0: "Pankow",
    key_1: "10439",
    key_2: "Erich-Weinert-Str. 6",
    key_3: "Praxis Dr. Häusler",
    key_4: "Dr. Elke Häusler",
    key_5: "Hausarzt",
    key_6: "laut Internet",
    key_7: "",
    key_8: "praxis- haeusler.impfen@gmx.net",
    key_9: "",
    key_10:
      "Bitte sehen Sie von telefonischen Anfragen ab. Mit Ihrer Em-Mail kommen Sie auf unsere Warteliste. Bitte bringen Sie zum Impftermin Ihren Impfausweis und die Verischertenkarte mit.",
    key_11: "https://www.praxis- elkehaeusler.de/",
  },
  {
    key_0: "Pankow",
    key_1: "13158",
    key_2: "Kastanienallee 38",
    key_3: "Praxis Reuter",
    key_4: "Thomas Reuter",
    key_5: "Hausärztin/Hausarzt",
    key_6: "siehe Homepage der Praxis: www.praxisreuter-berlin.de",
    key_7: "",
    key_8: "info@praxisreuter-berlin.de",
    key_9: "",
    key_10:
      "Termine bitte per E-Mail vereinbaren, nur ausnahmsweise per Telefon. Frauen unter 60 Jahren impfe ich nicht mit AstraZeneca",
    key_11: "www.praxisreuter-berlin.de",
  },
  {
    key_0: "Pankow",
    key_1: "13187",
    key_2: "Pichelswerderstr. 4",
    key_3: "Arztpraxis für Allgemeinmedizin",
    key_4: "Astrid Naumann",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Reine Impfsprechstunden Di Fr 11-13 Uhr",
    key_7: "",
    key_8: "",
    key_9: "Website/Samedi",
    key_10: "Bis auf weiteres keine telefonische Terminvereinbarungen!",
    key_11: "https://astrid-naumann.de/",
  },
  {
    key_0: "Pankow",
    key_1: "13467",
    key_2: "Greifswalder Straße 139",
    key_3: "MVZ Ambulantes Gynäkologisches OP-Zentrum",
    key_4: "Altankhuyag Otgonbold",
    key_5: "Gynäkologie",
    key_6: "Montags und eventuell Samstags",
    key_7: "",
    key_8: "",
    key_9: "www.gyn-opz.de",
    key_10: "Ein Termin kann über unsere Website gebucht werden: Doctolib",
    key_11: "https://www.ambulantes- gynaekologisches- operationszentrum.de/",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13409",
    key_2: "Residenzstr. 33",
    key_3: "Praxis für Urologie Dr. med. Talebi",
    key_4: "Ali Talebi",
    key_5: "Urologie",
    key_6:
      "Mo: 9-13 und 15-18 Uhr Di: 9-15 Uhr Mi: 9-12 Uhr Do: 9- 13 und 15-18 Uhr Fr: 9-12 Uhr",
    key_7: "",
    key_8: "residenzurologie@yahoo.de",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13437",
    key_2: "Tessenowstr. 56/57",
    key_3: "Hausarztpraxis Dr. Jahn",
    key_4: "Dr. Gerhard Jahn",
    key_5: "Hausärztin/Hausarzt",
    key_6:
      "Montag - Freitag 8 - 12 Uhr Montag, Dienstag, Donnerstag 16 - 18 Uhr",
    key_7: "030 / 414 18 01",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13435",
    key_2: "Wilhelmsruher Damm 231- 245",
    key_3: "Gesundheitszentrum Wittenau",
    key_4: "Siarhei Barysik",
    key_5: "Hausarzt",
    key_6:
      "Mo. 09:00-18:00 / Di. 09:00- 16:00 / Mi. 08:00-14:00 / Do. 09:00-16:30 / Fr. 08:00- 13:00",
    key_7: "030 / 265 868 00",
    key_8: "gz-wittenau@helios- gesundheit.de",
    key_9: "",
    key_10:
      "Parken auf dem Bauhaus Parkplatz möglich, Praxis Zugang: rechts vom Bauhaus Haupteingang, Impfärzte: Herr Barysik, Herr Dienert, Dokumente die zur Impfung mitzubringen sind: Chipkarte, wenn vorhanden: Impfpass, Einwilligungserklärung, Anamnesebogen Terminbuchung auch über die Webseite möglich, hierzu orthop. Sprechstunde nutzen. Bitte bei Bemerkung: Impfung eintragen",
    key_11:
      "https://www.helios- gesundheit.de/ambulant/berlin- wittenau-gesundheitszentrum- hausaerztliche-versorgung- othopaedie-akupunktur/",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13467",
    key_2: "Robinienweg 2",
    key_3: "Praxis Dr. Reiche",
    key_4: "Dr. Josephine Reiche",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Montag bis Donnerstag 8-18 Uhr Freitag 8-12 Uhr",
    key_7: "",
    key_8: "rezepte@drreiche.de",
    key_9: "-",
    key_10:
      "Kontakt ausschließlich per E-Mail (nur) unter rezepte@drreiche.de. Wir melden uns dann mit einem Terminvorschlag, sofern ausreichend Impfstoff vorhanden ist.",
    key_11: "www.drreiche.de",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13567",
    key_2: "Schloßstr.33",
    key_3: "Dr.med. J.Grambauer/Dr.med. B.Ritter",
    key_4: "Dr.Joachim Grambauer/ Dr.Bertram Ritter",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Mo.-Fr. 9.00h-13.00h / Mo.- Mi. 14.00h - 18.00h",
    key_7: "",
    key_8: "info@orthopaede-hermsdorf.de",
    key_9: "",
    key_10:
      "Impfausweis;Allergieausweis;Medikamentenplan;Internistische Diagnosen",
    key_11: "https://www.orthopaede- hermsdorf.de/",
  },
  {
    key_0: "Spandau",
    key_1: "13597",
    key_2: "Markt 1",
    key_3: "HNO-Praxis Dr. Mercks",
    key_4: "Dr. Heinz-Peter Mercks",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6: "Mo,Di,Do 9-12,15-18 / Mi 10-12 / Fr 9-13",
    key_7: "030 / 333 21 56",
    key_8: "hno-mercks@mailbox.org",
    key_9: "",
    key_10:
      "Aufklärungs- und Einwilligungserklärung für Vektor-Impfstoffe (AstraZeneca),download unter www.rki.de, bitte vollständig ausfüllen und unterschreiben",
    key_11:
      "https://www.hno-aerzte-im- netz.de/aerzte/berlin/berlin_me rcks/startseite.html",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12163",
    key_2: "Schloßstr. 28",
    key_3: "HNO Praxis Dr. Kai Müller",
    key_4: "Dr.med. Kai Müller",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6: "siehe unter www.hno-arzt- mueller.de",
    key_7: "",
    key_8: "covidimpfung@hno-arzt- mueller.de",
    key_9: "",
    key_10:
      "Astrazeneca wird bei uns Montags verimpft. Bitte vereinbaren Sie per E- Mail unter Angabe Ihrer Mobilnummer rechtzeitig einen Termin im vorab.",
    key_11: "www.hno-arzt-mueller.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12207",
    key_2: "Königsberger Str. 46",
    key_3: "Elke Köchy",
    key_4: "Elke Köchy",
    key_5: "Kinder- und Jugendmedizin",
    key_6:
      "Mo: 9-13 und 14-18 / Di: 9- 13 und 14-18 / Mi: 9-13 und 14-18 / Do: 9-13 und 14-18 / Fr: 9-13 und 14-17",
    key_7: "",
    key_8: "kontakt@kinderpraxis-koechy.de",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12163",
    key_2: "Düppelstr. 39",
    key_3: "Praxis für Orthopädie",
    key_4: "Dr. med. Marcus Hollenstein",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Mo,Di, Do, Fr: 8-12 Mo,Di,Do: 15-18",
    key_7: "030 / 790 88 70",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "www.dr-hollenstein.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12249",
    key_2: "Gallwitzalle 123-143",
    key_3: "MVZ am St. Marien - Krankenhaus",
    key_4: "Ziber Alija",
    key_5: "Innere Medizin (fachärztliche Versorgung)",
    key_6: "Siehe Webseite www.mvz- lankwitz.de",
    key_7: "030 / 767 83 570",
    key_8: "",
    key_9: "www.mvz-lankwitz.de",
    key_10: "",
    key_11: "www.mvz-lankwitz.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "14195",
    key_2: "Clayallee 175",
    key_3: "Bonedoctor",
    key_4: "Christian Rose",
    key_5: "Chirurgie-Orthopädie",
    key_6: "siehe Webseite",
    key_7: "",
    key_8: "corona-ex@bonedoctor.de",
    key_9: "https://www.bonedoctor.de",
    key_10: "",
    key_11: "https://www.bonedoctor.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "14195",
    key_2: "Clayallee 177",
    key_3: "HNO-Praxis Osterland",
    key_4: "Daniel Osterland",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6:
      "Mo 9:00-17:00 Uhr Di 9:00-17:00 Uhr Mi 9:00-14:00 Uhr Do 15:00-19:00 Uhr Fr 9:00-14:00 Uhr",
    key_7: "030 / 208 980 43 21",
    key_8: "termin@hno-osterland.de",
    key_9: "",
    key_10:
      "Bitte beachten: Die Impfung können wir nur nach vorheriger Terminvereinbarung durchführen.",
    key_11: "www.hno-osterland.de",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "10777",
    key_2: "Nollendorfstr. 17",
    key_3: "Praxis Dr. Kräutlein",
    key_4: "Dr. Katharina Kräutlein",
    key_5: "Hausärztin/Hausarzt",
    key_6: "siehe Internetpräsenz: www.katharina- kraeutlein.de",
    key_7: "",
    key_8: "praxis@katharina-kraeutlein.de",
    key_9: "",
    key_10: "",
    key_11: "www.katharina-kraeutlein.de",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "10785",
    key_2: "Kurfürstenstr 23",
    key_3: "Gemeinschaftspraxis Kurfürstenstr",
    key_4: "Dr. Yang-Lyreal Ser/Peter Berning",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo-Frei: 8.30 - 12.30 Uhr Mi: 13.00 - 18.00Uhr",
    key_7: "",
    key_8: "",
    key_9: "Website/Samedi",
    key_10: "Bitte bis auf Weiteres keine telefonischen Terminvereinbarungen!",
    key_11: "https://astrid-naumann.de/",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "12105",
    key_2: "Königstr. 27",
    key_3: "Dr. Sebastian Horowski",
    key_4: "Sebastian Horowski",
    key_5: "Hausarzt",
    key_6:
      "Montag, Dienstag, Mittwoch, Donnerstag und Freitag 8 .00- 12.00 Uhr Montag, Dienstag und Donnerstag 15.30 - 18.00 Uhr",
    key_7: "",
    key_8: "",
    key_9: "",
    key_10:
      "Anmeldung nur persönlich in der Praxis möglich Informationen auch gerne über unsere Website www.praxis-horowski.de",
    key_11: "",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "12159",
    key_2: "Fregestr. 74 a",
    key_3: "Dr. med. Andreas Kärsten",
    key_4: "Andreas Kärsten",
    key_5: "Hausarzt",
    key_6:
      "Impfsprechstunden: Montag 13.00 - 15.00 Uhr / Mittwoch 11.00 - 13.00 Uhr / Freitag: 13.00 - 14.00 Uhr",
    key_7: "030 / 859 11 44",
    key_8: "",
    key_9: "",
    key_10:
      "Terminvereinbarung NUR MONTAGS in der Zeit von 13.00 - 15.00 Uhr. Terminvereinbarungen sind dann nur für die laufende, evtl. noch die darauffolgende, Woche aufgrund geringer Impfmengen möglich. Erste Terminvereinbarung ab 03.05.2021 (Vakzinlieferung vorausgesetzt) Impfwillige bringen zum Termin bitte die Versichertenkarte und das Impfbuch (wenn vorhanden) mit. Außerdem bitten wir alle Impfwilligen unter 60 Jahren zum Termin eine Einverständniserklärung zur Impfung mit AstraZeneca mitzubringen.",
    key_11: "",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "12309",
    key_2: "Skarbinastraße 79",
    key_3: "Dr. Mattern",
    key_4: "Dr. Dirk Mattern",
    key_5: "Gynäkologie",
    key_6:
      "Montag + Mittwoch: 8-14 Uhr / Dienstag + Donnerstag: 13-19 Uhr / Freitag: 8-13 Uhr",
    key_7: "030 / 745 50 70",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12435",
    key_2: "Am Treptower Park 54",
    key_3: "Arztpraxis Hildemann",
    key_4: "Dipl.-Med. Sieglinde Hildemann",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Siehe: Praxis- hildemann.berlin",
    key_7: "",
    key_8: "kontakt@praxis- hildemann.berlin",
    key_9: "",
    key_10: "",
    key_11: "https://praxis- hildemann.berlin/startseite.html",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12487",
    key_2: "Segelfliegerdamm 95",
    key_3: "Jörg Heßling",
    key_4: "Dr Jörg Heßling",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo: 7-12 / Di: 10-18 Uhr / Mi 7-12 Uhr / Do 10-19 Uhr/ Fr 7-11 Uhr",
    key_7: "030 / 288 365 62",
    key_8: "",
    key_9: "",
    key_10:
      "Bitte mitbringen: Impfausweis, Versichertenkarte; Aufklärungs- und Anamneseformular für AstraZeneka-Impfung (Download über RKI- Webseite), sofern möglich.",
    key_11: "https://www.onkologie- segelfliegerdamm.de",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12489",
    key_2: "Albert-Einstein-Straße 2",
    key_3: "Hausarztpraxis Adlershof",
    key_4: "Dr. med. Gilbert Büchner",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Die aktuellen Öffnungszeiten finden Sie auf unserer Webseite.",
    key_7: "",
    key_8: "",
    key_9: "",
    key_10:
      "Bitte tragen Sie sich auf unserer Webseite in die Warteliste für eine Corona- Schutzimpfung mit AstraZeneca ein.",
    key_11: "http://www.hausarztpraxis- adlershof.de",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12489",
    key_2: "Albert-Einstein-Straße 2",
    key_3: "Praxis Dr. Ertelt",
    key_4: "Dr Konstanze Ertelt",
    key_5: "Hausarzt",
    key_6:
      "Mo: 9 bis 14 Uhr / Di: 9 bis 13 Uhr / Mi: 9 bis 12 Uhr / Do: 11.30 bis 15 Uhr / Fr : 8.30 bis 12 Uhr sowie Impftermine nach Vereinbarung ausserhalb der Sprechzeiten",
    key_7: "",
    key_8: "kontakt@onlinepraxis.berlin",
    key_9: "",
    key_10:
      "Bitte bringen Sie den Aufklärungschein, Anamnesebogen für Neupatienten und die Einwilligung ausgefüllt mit.",
    key_11: "https://www.onlinepraxis.berlin /",
  },
  {
    key_0: "Bezirk",
    key_1: "PLZ",
    key_2: "Straße und Hausnummer",
    key_3: "Name der Praxis",
    key_4: "Vor- und Zuname der Ärztin/des Arztes",
    key_5: "Fachgebiet",
    key_6: "Sprechzeiten",
    key_7: "Terminbuchung telefonisch unter:",
    key_8: "Terminbuchung per E-Mail unter:",
    key_9: "Terminbuchung online unter:",
    key_10: "",
    key_11: "Weitere Informationen für Impfwillige",
    key_12: "Website der Arztpraxis, falls vorhanden",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10625",
    key_2: "Bismarckstr. 95/96",
    key_3: "MVZ Dr. Kaleth und Kollegen",
    key_4: "Sabine Eigenwillig",
    key_5: "Hausarzt",
    key_6: "Mo.-Fr. 8:00-18:00",
    key_7: "030 / 801 051 50",
    key_8: "info@kaleth-und-kollegen.de",
    key_9: "https://www.doctolib.de/allgemeinm",
    key_10: "",
    key_11: "",
    key_12: "https://www.kalethundkollegen.",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10629",
    key_2: "Schlüterstraße 38",
    key_3: "Praxis Wünsche",
    key_4: "Thoms Wünsche",
    key_5: "Hausarzt",
    key_6:
      "Mo: 8:00-12:30 und 14:00- 19:00 / Di: 8:00-12:30 und 14:00-19:00 / Mi: 7:00- 14:00 / Do: 08:00-12:30 und 14:00-19:00 / Fr: 7:00-14:00",
    key_7: "030 / 885 643 0",
    key_8: "service@praxis-wuensche.com",
    key_9: "www.praxis-wuensche.com",
    key_10: "",
    key_11: "",
    key_12: "https://www.praxis- wuensche.com/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10629",
    key_2: "Dahlmannstr. 7",
    key_3: "Internisten Schlich u. Schorn",
    key_4: "Dr. Kai Schorn",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo,Di,Do 8:00-18:00 Uhr Mi,Fr 8:00-12:00 Uhr",
    key_7: "doctolib",
    key_8: "",
    key_9: "doctolib",
    key_10: "",
    key_11:
      "Keine Impfung bei Menschen unter 30 Jahren. Impfpass, Aufklärungsbogen und Einwilligung (über doctolib ) müssen mitgebracht werden.",
    key_12: "www.internisten.berlin",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10709",
    key_2: "Westfälische Str. 32",
    key_3: "Dr.med.Marlies Machens, Dr.med. Laura Freier",
    key_4: "Dr.med.Marlies Machens, Dr.med. Laura Freier",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Impfsprechstunde: Donnerstag: 11:05-11:50h, 15:00-15:50h",
    key_7: "030 / 895 412 91",
    key_8: "mail@dieinternistin.de",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "https://dieinternistin.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10717",
    key_2: "Bundesallee 185",
    key_3: "Aksü und Seeberger",
    key_4: "Uwe Seeber Tansel Aksü",
    key_5: "Hausärztin/Hausarzt",
    key_6:
      "Montag 9- 14 Uhr und 16 bis 18:00 / Dienatsg 9-14 Uhr und 16- 18:00 / Mittwoch 9 - 12:00 Uhr / Donnerstag 9-14:00 Uhr und 16 - 18:00 Uhr / Freitag 9- 13:00 Uhr",
    key_7: "030 / 218 46 44",
    key_8: "info@praxis-online.biz",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "10789",
    key_2: "Rankestraße 8",
    key_3: "MVZ Rankestrasse GmbH",
    key_4: "Dr. Christine Sommerfeld/ Dr. Natascha Hess",
    key_5: "Innere Medizin (fachärztliche Versorgung)",
    key_6:
      "Mo: 9-16 Uhr / Di: 9-15 Uhr / Do: 8-15 Uhr / Fr: 8-13 Uhr Bitte immer nur nach Vereinbarung kommen !",
    key_7: "",
    key_8: "kontakt@mvz-rankestrasse.de",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "https://mvz- rankestrasse.de/aktuelles.html",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Charlottenburg- Wilmersdorf",
    key_1: "13627",
    key_2: "Reichweindamm 31",
    key_3: "PD Dr. med. Petra Koehne, Fachärzte für Kinder- und Jugendmedizin",
    key_4: "Petra Koehne",
    key_5: "Kinder- und Jugendmedizin",
    key_6:
      "Montag, Dienstag und Donnerstag 09:00-12:00, 15:00-18:00 / Mittwoch 09:00-12:00 / Donnerstag 09:00-12:00, 15:00-18:00 / Freitag 09:00-18:00",
    key_7: "030 / 345 207 1/2",
    key_8: "Praxisteam_Koehne@web.de",
    key_9: "Doctolib",
    key_10: "",
    key_11:
      "Impftermine werden derzeit v.a. am Dienstag und Donnerstag Vormittag, sowie am Mittwoch und Freitag Nachmittag vergeben. Die angebotenen Impfzeiten richten sich v.a. nach der Verfügbarkeit der Impfstoffe. Zum Impftermin mitzubringen sind die Versichertenkarte, der unterschriebene Aufklärungs- und Einwilligungsbogen für die Covid-Impfung (erhältlich auf der Webseite des RKI) und das Impfbuch (sofern vorhanden).",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Matthiasstraße 7",
    key_3: "Facharztzentrum am Friedrichshain",
    key_4: "Dr. med. Knut Krenkel",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Termine nur nach Vereinbarung",
    key_7: "",
    key_8: "corona@facharztzentrum- friedrichshain.de",
    key_9: "Doctolib",
    key_10: "",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Matthiasstraße 7",
    key_3: "Facharztzentrum am Friedrichshain",
    key_4: "Sven Holleck-Weithmann",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6: "Termine nur nach Vereinbarung",
    key_7: "",
    key_8: "corona@facharztzentrum- friedrichshain.de",
    key_9: "Doctolib",
    key_10: "",
    key_11: "",
    key_12: "https://www.facharztzentrum- friedrichshain.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Petersburger Str. 72A",
    key_3: "Chirurgische Praxis",
    key_4: "Dr. Thomas Hofmann",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Freitags",
    key_7: "",
    key_8: "hofmann@hofmann-wierth.de",
    key_9: "",
    key_10: "",
    key_11: "Keine telefonische Anmeldung möglich.",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10249",
    key_2: "Petersburger Str. 72A",
    key_3: "chirurgische Praxis Friedrichshain",
    key_4: "Dr. Thomas Hofmann, Dr. Andre Wierth, Robert Krause",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Freitags 12:00-14:30",
    key_7: "",
    key_8: "hofmann@hofmann-wierth.de",
    key_9: "",
    key_10: "",
    key_11: "Impftermine werden auf keine Fall telefonisch vergeben!",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Friedrichshain- Kreuzberg",
    key_1: "10999",
    key_2: "Kottbusser Straße 16,",
    key_3: "Arztpraxis Dr. Buck",
    key_4: "Dr. Elfriede Buck",
    key_5: "Hausarzt",
    key_6:
      "Montag 10-17 Uhr / Dienstag, Mittwoch, Freitag 10-13 Uhr / Donnerstag 10- 18 Uhr Impfungen erfolgen außerhalb der o.g. Sprechzeiten",
    key_7: "030 / 611 80 76",
    key_8: "",
    key_9: "https://www.doctolib.de/allgemeinm",
    key_10: "",
    key_11:
      "Bitte EInverständniserklärung, Anamnese und Aufklärungsmerkblatt für Vektorimpfstoff ausgefüllt mitbringen (auf der Webseite des RKI erhältlich)",
    key_12: "http://praxisdrbuck.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Lichtenberg",
    key_1: "10315",
    key_2: "Rummelsburgerstr. 13-15",
    key_3: "Facharztpraxis für Allgemeinmedizin",
    key_4: "Dipl. Med. Angela Nöther",
    key_5: "Hausarzt",
    key_6:
      "AstraZeneca-Impfungen außerhalb der Priorisierung ab 03.05.2021 in unserer Praxis möglich, Terminvergabe ausschließlich telefonisch möglich.",
    key_7: "030 / 510 10 13",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11:
      "Für die Impfungen mit dem Astra Impfstoff stehen ausschließlich fixe Termine zur Verfügung, die Ihnen vom Personal angeboten werden. Diese sind abhängig von den Lieferungen des Impfstoffs. Die Impfung von Patienten unter 60 Jahren erfolgt nur auf ausdrücklichen Wunsch des Patienten nach entsprechender Aufklärung. Halten Sie Ihren Impfausweis bereit, kleiden Sie sich bitte praktisch, um lange Wartezeiten zu vermeiden.",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Lichtenberg",
    key_1: "10318",
    key_2: "Rheinsteinstr. 1",
    key_3: "Hausarztpraxis Choi",
    key_4: "Kwang Ryul Choi",
    key_5: "Hausarzt",
    key_6: "Mo-Fr 8:00 -12:00 / Nur Mo und Do 14:00 - 18:00",
    key_7: "030 / 509 01 62",
    key_8: "praxischoi@gmx.de",
    key_9: "",
    key_10: "",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Lichtenberg",
    key_1: "10365",
    key_2: "Schulze-Boysen-Straße 35",
    key_3: "Bugenhagen",
    key_4: "Kristin Bugenhagen",
    key_5: "Hausarzt",
    key_6: "Impftag: Mittwochs 07-12 Uhr und nach Vereinbarung",
    key_7: "030 / 553 66 55",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "oder geben Sie unter Tel-Nr Ihren Namen und Rückrufnummer an",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Marzahn-Hellersdorf",
    key_1: "12627",
    key_2: "Hellersdorfer Str. 237",
    key_3: "MVZ für Gynäkologie Helle-Mitte",
    key_4: "Dr. med. Muna Zaghloul-Abu Dakah",
    key_5: "Gynäkologie",
    key_6: "Mo-Do 08:00 - 18:00 / Fr. 08:00 - 12:00",
    key_7: "030 / 290 256 877 030 / 451 99 481 030 / 455",
    key_8: "info@berliner-frauenarzt.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte bringen Sie Ihren Impfausweis und die Versichertenkarte mit. Bei Gerinnungsstörungen bitten wir um Kopien der Befunde.",
    key_12: "www.berliner-kinderwunsch.de",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Seestrasse, 99",
    key_3: "Praxis Tambag",
    key_4: "Sultan Tambag",
    key_5: "Hausärztin/Hausarzt",
    key_6:
      "Montag 8:00-13:00 und 15:00-18:00 Dienstag 8:00-13:00 und 15:00-18:00",
    key_7: "im pftermincorona@gmail.com",
    key_8: "",
    key_9: "",
    key_10:
      "Krankenversicherungskarte, Einverständniserklärung Aufklärungsbogen von der Homepage des Robert-Koch-Instituts",
    key_11: "",
    key_12: "",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Lydia Yamin",
    key_5: "Hausarzt",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Mahmoud Pakzad",
    key_5: "Hausarzt",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Peter Velling",
    key_5: "Hausarzt",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Petra Itain",
    key_5: "Hausarzt",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Manuel Moscovici",
    key_5: "Radiologie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10: "",
    key_11:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_12: "https://medico-leopoldplatz.de/",
    key_13: "",
    key_14: "",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Levent Emre",
    key_5: "Radiologie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Jens Alter",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Barbara Schulze",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Afschin Mirschekarnejad",
    key_5: "Chirurgie-Orthopädie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Matthias Bräuer",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Montag bis Freitag 08:00 bis 20:00 Uhr Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin den von Ihnen ausgefüllten Aufklärungs- und Anamnesebogen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Müllerstraße 151",
    key_3: "Medico Leopoldplatz GmbH",
    key_4: "Dr. Andreas Schief",
    key_5: "Chirurgie-Orthopädie",
    key_6:
      "Montag bis Freitag 08:00 bis 20:00 Uhr / Samstag 08:00 bis 16:00 Uhr",
    key_7: "030 / 457 97 90",
    key_8: "termine@medico- leopoldplatz.de",
    key_9: "",
    key_10:
      "Bitte informieren Sie sich vor Ihrem Termin über die aktuellen Hinweise zum Impfprocedere in unserer Praxis. Weitere Informationen finden Sie unter: https://medico-leopoldplatz.de/corona-covid-19-impfung/ Bringen Sie bitte, wenn möglich, zum Termin die von Ihnen ausgefüllten Aufklärungs- und Anamnesebögen mit.",
    key_11: "https://medico-leopoldplatz.de/",
  },
  {
    key_0: "Mitte",
    key_1: "13353",
    key_2: "Lütticher Str. 13",
    key_3: "Praxis Dr. med. Aref Sharafi",
    key_4: "Aref Sharafi",
    key_5: "Innere Medizin (fachärztliche Versorgung)",
    key_6:
      "Montag bis Freitag 09:00- 13:00 Uhr / Montag, Dienstag und Donnerstag 15:00-18:00 Uhr",
    key_7: "030 / 454 90 303",
    key_8: "Sharafi.2018@web.de",
    key_9: "",
    key_10:
      "Liebe Patienten/innen, gerne können Sie sich telefonisch oder per E-Mail unter den aufgelisteten Kontaktdaten, für eine Impfung amelden.",
    key_11: "https://dr-aref- sharafi.business.site/",
  },
  {
    key_0: "Neukölln",
    key_1: "12043",
    key_2: "Karl-Marx-Str., 80",
    key_3: "Tengis Kasch",
    key_4: "Tengis Kasch",
    key_5: "Gynäkologie",
    key_6: "Mo und Di nach Vereinbarung",
    key_7: "030 / 681 50 41",
    key_8: "tengis.kasch@dgn.de",
    key_9: "",
    key_10: "",
    key_11: "https://www.frauenarzt- berlin.de/",
  },
  {
    key_0: "Neukölln",
    key_1: "12043",
    key_2: "Karl-Marx-Straße 78",
    key_3: "Arztpraxis Asafu-Adjaye",
    key_4: "John G. Asafu-Adjaye",
    key_5: "Hausarzt",
    key_6:
      "Montag, Dienstag, Donnerstag von 9 - 13 Uhr und 16 - 18 Uhr / Mittwoch und Freitag von 9 - 13 Uhr",
    key_7: "030 / 623 47 39",
    key_8: "arztpraxis-asafu-adjaye@web.de",
    key_9: "",
    key_10: "Termine zurzeit nur nach vorheriger Vereinbarung.",
    key_11:
      "https://www.arztpraxis-asafu- adjaye.de/praxis/herzlich- willkommen.html",
  },
  {
    key_0: "Neukölln",
    key_1: "12047",
    key_2: "Bürknerstraße 32",
    key_3: "Praxis am Maybachufer - Dr. med. Stefan Karakaya",
    key_4: "Stefan Karakaya",
    key_5: "Hausarzt",
    key_6: "siehe Praxishomepage",
    key_7: "",
    key_8: "",
    key_9: "www.praxis-am-maybachufer.de",
    key_10: "Terminvereinbarung für AstraZeneca ausschließlich online",
    key_11: "https://www.praxis-am- maybachufer.de/de/",
  },
  {
    key_0: "Neukölln",
    key_1: "12055",
    key_2: "Böhmische Str. 45",
    key_3: "Michaud",
    key_4: "Larissa",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo-Fr 9:00 - 12:00 Mo. Di. u. Do. 15:00 - 17:00",
    key_7: "030 / 684 34 77",
    key_8: "dr.michaud@t-online.de",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Neukölln",
    key_1: "12349",
    key_2: "Christoph-Ruden-Strasse 7",
    key_3: "HNO-Facharztpraxis",
    key_4: "Sousan Moghaddam",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6:
      "Montag: 9.00 - 12.00 und 14.00 - 18.00 Uhr Dienstag: 9.00 - 13.00 Uhr Mittwoch: 9.00 - 15.00 Uhr Donnerstag: 12.00 - 18.00 Uhr Freitag: 9.00 - 12. 00 Uhr",
    key_7: "030 / 698 15 041",
    key_8: "arzt@hno-moghaddam.de",
    key_9: "",
    key_10:
      "AstraZeneca für Impfwillige ab 60 Jahren, unter 60jährige freiwillig impfende Ärztinnen: Sousan Moghaddam, Sabine Baran",
    key_11: "www.hno-moghaddam.de",
  },
  {
    key_0: "Neukölln",
    key_1: "12349",
    key_2: "Alt-Buckow 9-11",
    key_3: "Hautarztpraxis",
    key_4: "Dres. Annette und Axel Köhler",
    key_5: "Haut- und Geschlechtskrankheiten",
    key_6: "Nach telefonischer oder persönlicher Absprache",
    key_7: "030 / 660 066 33",
    key_8: "",
    key_9: "",
    key_10:
      "Impfausweis mitbringen Ausgefüllter Aufklärungsbogen (unterschrieben), Anamnese und Einverständniserklärung unterschrieben mitzubringen",
    key_11: "https://berlin-derma.de/",
  },
  {
    key_0: "Pankow",
    key_1: "10437",
    key_2: "Stargarder Str.69/ Eberswalder Str.33",
    key_3: "die hausärzte",
    key_4: "Silke Weck",
    key_5: "Hausarzt",
    key_6:
      "Mo-Fr: 11-13 Uhr in 10437 Berlin, Eberswalder Str.33 (auf dem Hof) - Impfung ausschließlich an diesem Standort - nur mit Termin",
    key_7: "0176 / 202 001 16",
    key_8: "",
    key_9: "www.die-hausaerzte.berlin",
    key_10:
      "Bringen Sie, wenn möglich, das ausgefüllte Aufklärungsmerkblatt und den ausgefüllten Anamnesebogen zum Termin mit. Diese erhalten Sie unter www.RKI.de/Informationsmaterial zum Impfen mit Vektorimpfstoff",
    key_11: "https://www.die- hausaerzte.berlin/",
  },
  {
    key_0: "Pankow",
    key_1: "10439",
    key_2: "Erich-Weinert-Str. 6",
    key_3: "Praxis Dr. Häusler",
    key_4: "Dr. Elke Häusler",
    key_5: "Hausarzt",
    key_6: "laut Internet",
    key_7: "",
    key_8: "praxis- haeusler.impfen@gmx.net",
    key_9: "",
    key_10:
      "Bitte sehen Sie von telefonischen Anfragen ab. Mit Ihrer Em-Mail kommen Sie auf unsere Warteliste. Bitte bringen Sie zum Impftermin Ihren Impfausweis und die Verischertenkarte mit.",
    key_11: "https://www.praxis- elkehaeusler.de/",
  },
  {
    key_0: "Pankow",
    key_1: "13158",
    key_2: "Kastanienallee 38",
    key_3: "Praxis Reuter",
    key_4: "Thomas Reuter",
    key_5: "Hausärztin/Hausarzt",
    key_6: "siehe Homepage der Praxis: www.praxisreuter-berlin.de",
    key_7: "",
    key_8: "info@praxisreuter-berlin.de",
    key_9: "",
    key_10:
      "Termine bitte per E-Mail vereinbaren, nur ausnahmsweise per Telefon. Frauen unter 60 Jahren impfe ich nicht mit AstraZeneca",
    key_11: "www.praxisreuter-berlin.de",
  },
  {
    key_0: "Pankow",
    key_1: "13187",
    key_2: "Pichelswerderstr. 4",
    key_3: "Arztpraxis für Allgemeinmedizin",
    key_4: "Astrid Naumann",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Reine Impfsprechstunden Di Fr 11-13 Uhr",
    key_7: "",
    key_8: "",
    key_9: "Website/Samedi",
    key_10: "Bis auf weiteres keine telefonische Terminvereinbarungen!",
    key_11: "https://astrid-naumann.de/",
  },
  {
    key_0: "Pankow",
    key_1: "13467",
    key_2: "Greifswalder Straße 139",
    key_3: "MVZ Ambulantes Gynäkologisches OP-Zentrum",
    key_4: "Altankhuyag Otgonbold",
    key_5: "Gynäkologie",
    key_6: "Montags und eventuell Samstags",
    key_7: "",
    key_8: "",
    key_9: "www.gyn-opz.de",
    key_10: "Ein Termin kann über unsere Website gebucht werden: Doctolib",
    key_11: "https://www.ambulantes- gynaekologisches- operationszentrum.de/",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13409",
    key_2: "Residenzstr. 33",
    key_3: "Praxis für Urologie Dr. med. Talebi",
    key_4: "Ali Talebi",
    key_5: "Urologie",
    key_6:
      "Mo: 9-13 und 15-18 Uhr Di: 9-15 Uhr Mi: 9-12 Uhr Do: 9- 13 und 15-18 Uhr Fr: 9-12 Uhr",
    key_7: "",
    key_8: "residenzurologie@yahoo.de",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13437",
    key_2: "Tessenowstr. 56/57",
    key_3: "Hausarztpraxis Dr. Jahn",
    key_4: "Dr. Gerhard Jahn",
    key_5: "Hausärztin/Hausarzt",
    key_6:
      "Montag - Freitag 8 - 12 Uhr Montag, Dienstag, Donnerstag 16 - 18 Uhr",
    key_7: "030 / 414 18 01",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13435",
    key_2: "Wilhelmsruher Damm 231- 245",
    key_3: "Gesundheitszentrum Wittenau",
    key_4: "Siarhei Barysik",
    key_5: "Hausarzt",
    key_6:
      "Mo. 09:00-18:00 / Di. 09:00- 16:00 / Mi. 08:00-14:00 / Do. 09:00-16:30 / Fr. 08:00- 13:00",
    key_7: "030 / 265 868 00",
    key_8: "gz-wittenau@helios- gesundheit.de",
    key_9: "",
    key_10:
      "Parken auf dem Bauhaus Parkplatz möglich, Praxis Zugang: rechts vom Bauhaus Haupteingang, Impfärzte: Herr Barysik, Herr Dienert, Dokumente die zur Impfung mitzubringen sind: Chipkarte, wenn vorhanden: Impfpass, Einwilligungserklärung, Anamnesebogen Terminbuchung auch über die Webseite möglich, hierzu orthop. Sprechstunde nutzen. Bitte bei Bemerkung: Impfung eintragen",
    key_11:
      "https://www.helios- gesundheit.de/ambulant/berlin- wittenau-gesundheitszentrum- hausaerztliche-versorgung- othopaedie-akupunktur/",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13467",
    key_2: "Robinienweg 2",
    key_3: "Praxis Dr. Reiche",
    key_4: "Dr. Josephine Reiche",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Montag bis Donnerstag 8-18 Uhr Freitag 8-12 Uhr",
    key_7: "",
    key_8: "rezepte@drreiche.de",
    key_9: "-",
    key_10:
      "Kontakt ausschließlich per E-Mail (nur) unter rezepte@drreiche.de. Wir melden uns dann mit einem Terminvorschlag, sofern ausreichend Impfstoff vorhanden ist.",
    key_11: "www.drreiche.de",
  },
  {
    key_0: "Reinickendorf",
    key_1: "13567",
    key_2: "Schloßstr.33",
    key_3: "Dr.med. J.Grambauer/Dr.med. B.Ritter",
    key_4: "Dr.Joachim Grambauer/ Dr.Bertram Ritter",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Mo.-Fr. 9.00h-13.00h / Mo.- Mi. 14.00h - 18.00h",
    key_7: "",
    key_8: "info@orthopaede-hermsdorf.de",
    key_9: "",
    key_10:
      "Impfausweis;Allergieausweis;Medikamentenplan;Internistische Diagnosen",
    key_11: "https://www.orthopaede- hermsdorf.de/",
  },
  {
    key_0: "Spandau",
    key_1: "13597",
    key_2: "Markt 1",
    key_3: "HNO-Praxis Dr. Mercks",
    key_4: "Dr. Heinz-Peter Mercks",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6: "Mo,Di,Do 9-12,15-18 / Mi 10-12 / Fr 9-13",
    key_7: "030 / 333 21 56",
    key_8: "hno-mercks@mailbox.org",
    key_9: "",
    key_10:
      "Aufklärungs- und Einwilligungserklärung für Vektor-Impfstoffe (AstraZeneca),download unter www.rki.de, bitte vollständig ausfüllen und unterschreiben",
    key_11:
      "https://www.hno-aerzte-im- netz.de/aerzte/berlin/berlin_me rcks/startseite.html",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12163",
    key_2: "Schloßstr. 28",
    key_3: "HNO Praxis Dr. Kai Müller",
    key_4: "Dr.med. Kai Müller",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6: "siehe unter www.hno-arzt- mueller.de",
    key_7: "",
    key_8: "covidimpfung@hno-arzt- mueller.de",
    key_9: "",
    key_10:
      "Astrazeneca wird bei uns Montags verimpft. Bitte vereinbaren Sie per E- Mail unter Angabe Ihrer Mobilnummer rechtzeitig einen Termin im vorab.",
    key_11: "www.hno-arzt-mueller.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12207",
    key_2: "Königsberger Str. 46",
    key_3: "Elke Köchy",
    key_4: "Elke Köchy",
    key_5: "Kinder- und Jugendmedizin",
    key_6:
      "Mo: 9-13 und 14-18 / Di: 9- 13 und 14-18 / Mi: 9-13 und 14-18 / Do: 9-13 und 14-18 / Fr: 9-13 und 14-17",
    key_7: "",
    key_8: "kontakt@kinderpraxis-koechy.de",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12163",
    key_2: "Düppelstr. 39",
    key_3: "Praxis für Orthopädie",
    key_4: "Dr. med. Marcus Hollenstein",
    key_5: "Chirurgie-Orthopädie",
    key_6: "Mo,Di, Do, Fr: 8-12 Mo,Di,Do: 15-18",
    key_7: "030 / 790 88 70",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "www.dr-hollenstein.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "12249",
    key_2: "Gallwitzalle 123-143",
    key_3: "MVZ am St. Marien - Krankenhaus",
    key_4: "Ziber Alija",
    key_5: "Innere Medizin (fachärztliche Versorgung)",
    key_6: "Siehe Webseite www.mvz- lankwitz.de",
    key_7: "030 / 767 83 570",
    key_8: "",
    key_9: "www.mvz-lankwitz.de",
    key_10: "",
    key_11: "www.mvz-lankwitz.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "14195",
    key_2: "Clayallee 175",
    key_3: "Bonedoctor",
    key_4: "Christian Rose",
    key_5: "Chirurgie-Orthopädie",
    key_6: "siehe Webseite",
    key_7: "",
    key_8: "corona-ex@bonedoctor.de",
    key_9: "https://www.bonedoctor.de",
    key_10: "",
    key_11: "https://www.bonedoctor.de",
  },
  {
    key_0: "Steglitz-Zehlendorf",
    key_1: "14195",
    key_2: "Clayallee 177",
    key_3: "HNO-Praxis Osterland",
    key_4: "Daniel Osterland",
    key_5: "Hals- Nasen- Ohrenheilkunde",
    key_6:
      "Mo 9:00-17:00 Uhr Di 9:00-17:00 Uhr Mi 9:00-14:00 Uhr Do 15:00-19:00 Uhr Fr 9:00-14:00 Uhr",
    key_7: "030 / 208 980 43 21",
    key_8: "termin@hno-osterland.de",
    key_9: "",
    key_10:
      "Bitte beachten: Die Impfung können wir nur nach vorheriger Terminvereinbarung durchführen.",
    key_11: "www.hno-osterland.de",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "10777",
    key_2: "Nollendorfstr. 17",
    key_3: "Praxis Dr. Kräutlein",
    key_4: "Dr. Katharina Kräutlein",
    key_5: "Hausärztin/Hausarzt",
    key_6: "siehe Internetpräsenz: www.katharina- kraeutlein.de",
    key_7: "",
    key_8: "praxis@katharina-kraeutlein.de",
    key_9: "",
    key_10: "",
    key_11: "www.katharina-kraeutlein.de",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "10785",
    key_2: "Kurfürstenstr 23",
    key_3: "Gemeinschaftspraxis Kurfürstenstr",
    key_4: "Dr. Yang-Lyreal Ser/Peter Berning",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo-Frei: 8.30 - 12.30 Uhr Mi: 13.00 - 18.00Uhr",
    key_7: "",
    key_8: "",
    key_9: "Website/Samedi",
    key_10: "Bitte bis auf Weiteres keine telefonischen Terminvereinbarungen!",
    key_11: "https://astrid-naumann.de/",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "12105",
    key_2: "Königstr. 27",
    key_3: "Dr. Sebastian Horowski",
    key_4: "Sebastian Horowski",
    key_5: "Hausarzt",
    key_6:
      "Montag, Dienstag, Mittwoch, Donnerstag und Freitag 8 .00- 12.00 Uhr Montag, Dienstag und Donnerstag 15.30 - 18.00 Uhr",
    key_7: "",
    key_8: "",
    key_9: "",
    key_10:
      "Anmeldung nur persönlich in der Praxis möglich Informationen auch gerne über unsere Website www.praxis-horowski.de",
    key_11: "",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "12159",
    key_2: "Fregestr. 74 a",
    key_3: "Dr. med. Andreas Kärsten",
    key_4: "Andreas Kärsten",
    key_5: "Hausarzt",
    key_6:
      "Impfsprechstunden: Montag 13.00 - 15.00 Uhr / Mittwoch 11.00 - 13.00 Uhr / Freitag: 13.00 - 14.00 Uhr",
    key_7: "030 / 859 11 44",
    key_8: "",
    key_9: "",
    key_10:
      "Terminvereinbarung NUR MONTAGS in der Zeit von 13.00 - 15.00 Uhr. Terminvereinbarungen sind dann nur für die laufende, evtl. noch die darauffolgende, Woche aufgrund geringer Impfmengen möglich. Erste Terminvereinbarung ab 03.05.2021 (Vakzinlieferung vorausgesetzt) Impfwillige bringen zum Termin bitte die Versichertenkarte und das Impfbuch (wenn vorhanden) mit. Außerdem bitten wir alle Impfwilligen unter 60 Jahren zum Termin eine Einverständniserklärung zur Impfung mit AstraZeneca mitzubringen.",
    key_11: "",
  },
  {
    key_0: "Tempelhof- Schöneberg",
    key_1: "12309",
    key_2: "Skarbinastraße 79",
    key_3: "Dr. Mattern",
    key_4: "Dr. Dirk Mattern",
    key_5: "Gynäkologie",
    key_6:
      "Montag + Mittwoch: 8-14 Uhr / Dienstag + Donnerstag: 13-19 Uhr / Freitag: 8-13 Uhr",
    key_7: "030 / 745 50 70",
    key_8: "",
    key_9: "",
    key_10: "",
    key_11: "",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12435",
    key_2: "Am Treptower Park 54",
    key_3: "Arztpraxis Hildemann",
    key_4: "Dipl.-Med. Sieglinde Hildemann",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Siehe: Praxis- hildemann.berlin",
    key_7: "",
    key_8: "kontakt@praxis- hildemann.berlin",
    key_9: "",
    key_10: "",
    key_11: "https://praxis- hildemann.berlin/startseite.html",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12487",
    key_2: "Segelfliegerdamm 95",
    key_3: "Jörg Heßling",
    key_4: "Dr Jörg Heßling",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Mo: 7-12 / Di: 10-18 Uhr / Mi 7-12 Uhr / Do 10-19 Uhr/ Fr 7-11 Uhr",
    key_7: "030 / 288 365 62",
    key_8: "",
    key_9: "",
    key_10:
      "Bitte mitbringen: Impfausweis, Versichertenkarte; Aufklärungs- und Anamneseformular für AstraZeneka-Impfung (Download über RKI- Webseite), sofern möglich.",
    key_11: "https://www.onkologie- segelfliegerdamm.de",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12489",
    key_2: "Albert-Einstein-Straße 2",
    key_3: "Hausarztpraxis Adlershof",
    key_4: "Dr. med. Gilbert Büchner",
    key_5: "Hausärztin/Hausarzt",
    key_6: "Die aktuellen Öffnungszeiten finden Sie auf unserer Webseite.",
    key_7: "",
    key_8: "",
    key_9: "",
    key_10:
      "Bitte tragen Sie sich auf unserer Webseite in die Warteliste für eine Corona- Schutzimpfung mit AstraZeneca ein.",
    key_11: "http://www.hausarztpraxis- adlershof.de",
  },
  {
    key_0: "Treptow-Köpenick",
    key_1: "12489",
    key_2: "Albert-Einstein-Straße 2",
    key_3: "Praxis Dr. Ertelt",
    key_4: "Dr Konstanze Ertelt",
    key_5: "Hausarzt",
    key_6:
      "Mo: 9 bis 14 Uhr / Di: 9 bis 13 Uhr / Mi: 9 bis 12 Uhr / Do: 11.30 bis 15 Uhr / Fr : 8.30 bis 12 Uhr sowie Impftermine nach Vereinbarung ausserhalb der Sprechzeiten",
    key_7: "",
    key_8: "kontakt@onlinepraxis.berlin",
    key_9: "",
    key_10:
      "Bitte bringen Sie den Aufklärungschein, Anamnesebogen für Neupatienten und die Einwilligung ausgefüllt mit.",
    key_11: "https://www.onlinepraxis.berlin /",
  },
];

export default data;
